In [2]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

dialogue = pd.read_csv("Dialogue.csv", encoding='latin1')
fact_dialogue = pd.read_csv('fact_dialogue_afinn.csv', encoding='latin1')
afinn_lexicon = pd.read_csv('Afinn.csv', encoding='latin1', delimiter=',')

# Convert AFINN lexicon to a dictionary
afinn_dict = dict(zip(afinn_lexicon['word'], afinn_lexicon['value']))

# Function to preprocess the text: tokenize, convert to lowercase, remove non-alphabetic words and stopwords
def preprocess(text):
    words = word_tokenize(text.lower())
    filtered_words = [word for word in words if word.isalpha() and word not in stopwords.words('english')]
    return filtered_words

# Function to calculate the sentiment score of a text based on the AFINN lexicon
def calculate_sentiment(text):
    words = preprocess(text)
    sentiment_score = sum(afinn_dict.get(word, 0) for word in words)
    return sentiment_score

# Merge the DataFrames on 'ID_DIALOGUE'
merged = pd.merge(fact_dialogue, dialogue, left_on='ID_DIALOGUE', right_on='Dialogue ID')

# Calculate sentiment for each dialogue 
merged['SENTIMENT_AFINN_NLTK'] = merged['Dialogue'].apply(calculate_sentiment)

# Save the updated DataFrame to a new CSV file
merged.to_csv('fact_dialogue_afinn_final.csv', index=False, encoding='latin1')

# Drop the redundant 'Dialogue' column from merged_df
merged_final = merged.drop(columns=['Dialogue', 'Dialogue ID', 'Chapter ID', 'Place ID', 'Character ID'])


# Save the updated DataFrame to a new CSV file
merged_final.to_csv('fact_dialogue_afinn_final.csv', index=False, encoding='utf-8')

# Display the first few rows to verify
merged_final.head()

,ID_CHARACTER,ID_SCENE,ID_PLACE,ID_DIALOGUE,SENTIMENT_AFINN,DIALOGUE_LENGTH,LOVE_COUNT,INSERTED_AT,UPDATED_AT,SENTIMENT_AFINN_NLTK
0,4,1,8,1,0.0,10,0,2024-05-21 14:58:42,2024-05-21 14:58:42,0
1,7,1,8,2,5.0,9,0,2024-05-21 14:58:42,2024-05-21 14:58:42,3
2,4,1,8,3,-2.0,9,0,2024-05-21 14:58:42,2024-05-21 14:58:42,-2
3,7,1,8,4,0.0,3,0,2024-05-21 14:58:42,2024-05-21 14:58:42,0
4,4,1,8,5,0.0,4,0,2024-05-21 14:58:42,2024-05-21 14:58:42,0

In [5]:
def preprocess(text):
    words = word_tokenize(text.lower())
    filtered_words = [word for word in words if word.isalpha() and word not in stopwords.words('english')]
    return filtered_words

def calculate_sentiment(text):
    words = preprocess(text)
    sentiment_score = sum(afinn_dict.get(word, 0) for word in words)
    return sentiment_score

# Merge the DataFrames on 'ID_DIALOGUE'
merged = pd.merge(fact_dialogue, dialogue, left_on='ID_DIALOGUE', right_on='Dialogue ID')

# Calculate sentiment for each dialogue in the merged DataFrame
merged['SENTIMENT_AFINN_NLTK'] = merged['Dialogue'].apply(calculate_sentiment)

# Drop the redundant 'Dialogue' column from merged_df
merged_final = merged.drop(columns=['Dialogue', 'Dialogue ID', 'Chapter ID', 'Place ID', 'Character ID' ]) # dalo by se udělat jednodušeji?

# Save the updated DataFrame to a new CSV file (optional)
merged_final.to_csv('fact_dialogue_afinn_final.csv', index=False, encoding='latin1')

# Display the first few rows to verify
merged_final.head()

,ID_CHARACTER,ID_SCENE,ID_PLACE,ID_DIALOGUE,SENTIMENT_AFINN,DIALOGUE_LENGTH,LOVE_COUNT,INSERTED_AT,UPDATED_AT,SENTIMENT_AFINN_NLTK
0,4,1,8,1,0.0,10,0,2024-05-21 14:58:42,2024-05-21 14:58:42,0
1,7,1,8,2,5.0,9,0,2024-05-21 14:58:42,2024-05-21 14:58:42,3
2,4,1,8,3,-2.0,9,0,2024-05-21 14:58:42,2024-05-21 14:58:42,-2
3,7,1,8,4,0.0,3,0,2024-05-21 14:58:42,2024-05-21 14:58:42,0
4,4,1,8,5,0.0,4,0,2024-05-21 14:58:42,2024-05-21 14:58:42,0